/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  life:[
    {
      type: 'category',
      label: '运动',
      items: [
        'life/sport/sport',
        'life/log'
      ],
    },
  ],
  tutorialSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'vue',
      link: {
        type: 'generated-index', // 引导页类型
        title: 'vue引导页', //名称
        description: '这是一个引导页面', //描述
        slug: '/category/docusaurus-vue', //显示路径
        keywords: ['guides'], //标签
      },
      items: [
          // 'knowledgeStructure/vue/index',
          'knowledgeStructure/vue/test',
          'knowledgeStructure/vue/vue'
      ],
    },
  ],
};

module.exports = sidebars;
